# ─── SEALED SECRETS ──────────────────────────────────────────────────────
# Sealed Secrets encrypts Kubernetes secrets
# Safe to store in Git!
# Only the cluster can decrypt

# ─── HOW TO CREATE SEALED SECRETS ────────────────────────────────────────
# 1. Install kubeseal:
#    brew install kubeseal  (Mac)
#    or download from GitHub releases
#
# 2. Install Sealed Secrets controller:
#    kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# 3. Create regular secret first:
#    kubectl create secret generic app-secret \
#      --namespace dodo-payments \
#      --from-literal=DB_USER=dodoadmin \
#      --from-literal=DB_PASSWORD=dodopassword123 \
#      --dry-run=client -o yaml > /tmp/secret.yaml
#
# 4. Seal it:
#    kubeseal --format yaml < /tmp/secret.yaml > sealed-secret.yaml
#
# 5. Delete temp file:
#    rm /tmp/secret.yaml
#
# 6. Apply sealed secret (safe to commit to Git!):
#    kubectl apply -f sealed-secret.yaml

# ─── EXAMPLE SEALED SECRET (template) ───────────────────────────────────
# NOTE: This is a TEMPLATE only!
# Real encrypted values are generated by kubeseal command above
# Do NOT use these placeholder values in production!
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: dodo-payments
spec:
  encryptedData:
    # These values are generated by kubeseal
    # Replace with your actual encrypted values
    DB_USER: "AgBy8hBR..."        # placeholder - replace with kubeseal output
    DB_PASSWORD: "AgCH7bK..."     # placeholder - replace with kubeseal output
    POSTGRES_DB: "AgDK9mL..."     # placeholder - replace with kubeseal output
    POSTGRES_USER: "AgEL0nM..."   # placeholder - replace with kubeseal output
    POSTGRES_PASSWORD: "AgFM1oN..." # placeholder - replace with kubeseal output
  template:
    metadata:
      name: app-secret
      namespace: dodo-payments
    type: Opaque