---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-alerts
  namespace: monitoring
  labels:
    alertmanagerConfig: slack
spec:
  route:
    receiver: slack-notifications
    groupBy:
      - alertname
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
      - receiver: slack-notifications
        matchers:
          - name: severity
            value: critical
      - receiver: slack-notifications
        matchers:
          - name: severity
            value: warning
  receivers:
    - name: slack-notifications
      slackConfigs:
        - apiURL:
            name: slack-webhook-secret
            key: webhook-url
          channel: "#alerts"
          sendResolved: true
          title: "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}"
          text: |
            {{ range .Alerts }}
            *Alert:* {{ .Annotations.summary }}
            *Severity:* {{ .Labels.severity }}
            *Description:* {{ .Annotations.description }}
            *Namespace:* {{ .Labels.namespace }}
            {{ end }}
